name: Cmake release

on:
  release:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make
        #clean #build
    # - uses: actions/upload-artifact@v2
    #   with:
    #     path: build/*.tar.gz
    #     name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
