name: Linux release

on:
  release:
    types: [created]
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make
        #clean #build
      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-linux_x86_64
          path: |
            rling
            dedupe
            getpass
            rehex
            splitlen
          if-no-files-found: warn
        if: ${{ !startsWith( github.ref, 'refs/tags/v' ) }}
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: rling
          body_path: Changes.md
        if: startsWith( github.ref, 'refs/tags/v' )
