name: Cygwin Build

on:
  release:
    types: [created]
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cygwin
      # uses: egor-tensin/setup-cygwin@v4
      uses: cygwin/cygwin-install-action@master
      with:
        packages: make mingw64-x86_64-gcc-core gcc-core
    - name: make
      run: make
    - name: Publish release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-windows_cygwin_x86_64
        path: "*.exe"
        if-no-files-found: warn
      if: ${{ !startsWith( github.ref, 'refs/tags/v' ) }}
    - name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: "*.exe"
        body_path: Changes.md
      if: startsWith( github.ref, 'refs/tags/v' )
